export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ONBOARDING: "/onboarding",
  DASHBOARD: "/dashboard",
  FUNDING: "/funding",
  FUNDING_UPLOAD: "/funding/upload",
  WALLET: "/wallet",
  WITHDRAW: "/withdraw",
  ORDERS: "/orders",
  LEGAL: "/legal",
  CONCIERGE: "/concierge",
  SUPPORT: "/support",
  PROFILE: "/profile",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_DEPOSITS: "/admin/deposits",
  ADMIN_LIQUIDITY: "/admin/liquidity",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_CONSOLE: "/admin/console",
  ADMIN_INBOX: "/admin/inbox",
  ADMIN_LEGAL: "/admin/legal",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
